# Site settings
# These are used to personalize your new site.
title: Jared R. Andraszek # your name here
logo: "/images/headshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2025)
  <br /><br />
  <a href="https://github.com/JaredAndraszek42/csci-portfolio/blob/master/Andraszek_Resume.pdf">View My Resume</a>
  <br /><br />
  <a href="www.linkedin.com/in/jared-andraszek">View My LinkedIn Profile</a>
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/stu/users/27535440">View my Handshake Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  JaredAndraszek42 # update with your username
google_analytics: G-R1HC26S9P4 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal